influxdb:
  image: influxdb:latest
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
  env_file:
    - 'env.influxdb'
  volumes:
    # Data persistency
    # mkdir -p ~/docker-influxdb-grafana/influxdb/data
    - ~/docker-influxdb-grafana/influxdb/data:/var/lib/influxdb

telegraf:
  image: telegraf:latest
  container_name: telegraf
  links:
    - influxdb
  volumes:
    # Data persistency
    # mkdir -p ~/docker-influxdb-grafana/telegraf/data
    - ~/docker-influxdb-grafana/telegraf/data/telegraf.conf:/etc/telegraf/telegraf.conf:ro

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
    - "3000:3000"
  env_file:
    - 'env.grafana'
  links:
    - influxdb
  volumes:
    # Data persistency
    # mkdir -p ~/docker-influxdb-grafana/grafana/data; chown 472:472 /srv/docker/grafana/data
    - ~/docker-influxdb-grafana/grafana/data:/var/lib/grafana
